# Generated by Django 3.2.4 on 2021-06-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('live', 'live'), ('pending', 'pending'), ('archived', 'archived')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('survey', 'survey'), ('discussion', 'discussion'), ('diary', 'diary')], max_length=10)),
                ('description', models.TextField()),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tile')),
            ],
        ),
    ]
